import Provider from '@/ui/Provider';
import '../styles/globals.css';
import { Inter } from 'next/font/google';
import Nav from '@/ui/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Auth Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <div className='main'>
          <div className='gradient' />
        </div>
          <main className='app'>
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
